version: '2'
name: blog_snake
services:
  mysql:
    build: ./mysql_docker
    ports:
      - "3701:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
      MYSQL_DATABASE: blog_db
    volumes:
        - "mysql-data:/var/lib/mysql"
  api:
    build: ./api_docker
    ports:
      - "3700:3000"
    depends_on:
      - mysql

volumes:
    mysql-data:
        driver: "local"